# Generated by Django 4.1.1 on 2023-11-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCompeticion', '0001_initial'),
        ('appEquipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('ciudad_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('norma', models.CharField(max_length=5)),
                ('pais_id', models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.pais')),
            ],
            options={
                'verbose_name_plural': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='encuentro',
            fields=[
                ('encuentro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('clima', models.CharField(max_length=4)),
                ('estado_jugado', models.CharField(choices=[('J', 'JUGADO'), ('N', 'NO JUGADO'), ('E', 'EN JUEGO'), ('S', 'SUSPENDIDO')], default='DI', max_length=2)),
                ('competicion_id', models.ForeignKey(db_column='competicion_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.competicion')),
                ('equipo_local', models.ForeignKey(db_column='equipo_local', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local', to='appEquipo.equipo')),
                ('equipo_visita', models.ForeignKey(db_column='equipo_visita', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visita', to='appEquipo.equipo')),
                ('fase', models.ForeignKey(db_column='fase', on_delete=django.db.models.deletion.CASCADE, related_name='fase', to='appCompeticion.fase')),
                ('grupo', models.ForeignKey(db_column='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='appCompeticion.grupo')),
            ],
            options={
                'verbose_name_plural': 'encuentro',
            },
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('estado_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'estado',
            },
        ),
        migrations.CreateModel(
            name='formacion',
            fields=[
                ('formacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'formacion',
            },
        ),
        migrations.CreateModel(
            name='tipo_evento',
            fields=[
                ('tipo_evento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.BooleanField()),
                ('logo_tipo_evento', models.ImageField(blank=True, default='jugador/logo_default.png', null=True, upload_to='jugador/')),
            ],
            options={
                'verbose_name_plural': 'tipo_evento',
            },
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('sede_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('fecha_inauguracion', models.DateField()),
                ('imagen', models.ImageField(blank=True, default='sede/imagen_default.png', null=True, upload_to='sede/')),
                ('estado', models.CharField(choices=[('SD', 'SUSPENDIDO DEFINITIVAMENTE'), ('DI', 'DISPONIBLE'), ('EM', 'EN MANTENIMIENTO'), ('ND', 'NO DISPONIBLE'), ('ST', 'SUSPENDIDO TEMPORALMENTE')], default='DI', max_length=2)),
                ('ciudad_id', models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.ciudad')),
            ],
            options={
                'verbose_name_plural': 'sede',
            },
        ),
        migrations.CreateModel(
            name='eventoPersona',
            fields=[
                ('evento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiempo_reglamentario', models.TimeField(null=True)),
                ('tiempo_extra', models.TimeField(null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('alineacion1_id', models.ForeignKey(db_column='alineacion_id1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alineacion1', to='appEquipo.alineacionequipo')),
                ('alineacion2_id', models.ForeignKey(db_column='alineacion_id2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alineacion2', to='appEquipo.alineacionequipo')),
                ('encuentro_id', models.ForeignKey(db_column='encuentro_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.encuentro')),
                ('tipo_evento_id', models.ForeignKey(db_column='tipo_evento_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.tipo_evento')),
            ],
            options={
                'verbose_name_plural': 'evento',
            },
        ),
        migrations.AddField(
            model_name='encuentro',
            name='sede_id',
            field=models.ForeignKey(blank=True, db_column='sede_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.sede'),
        ),
        migrations.CreateModel(
            name='descripcion_encuentro',
            fields=[
                ('descripcion_encuentro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_equipo', models.CharField(blank=True, max_length=10, null=True)),
                ('goles', models.CharField(max_length=4)),
                ('goles_ronda_penales', models.CharField(max_length=4)),
                ('resultado', models.CharField(choices=[('G', 'GANADO'), ('E', 'EMPATADO'), ('P', 'PERDIDO')], max_length=1)),
                ('encuentro', models.ForeignKey(blank=True, db_column='encuentro_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_encuentros', to='appPartido.encuentro')),
                ('equipo', models.ForeignKey(blank=True, db_column='equipo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_encuentros', to='appEquipo.equipo')),
                ('formacion', models.ForeignKey(blank=True, db_column='formacion_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_encuentros', to='appPartido.formacion')),
            ],
            options={
                'verbose_name_plural': 'descripcion_encuentro',
            },
        ),
    ]
