# Generated by Django 4.1.1 on 2023-11-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='imagen',
            field=models.ImageField(blank=True, default='sede/imagen_default.png', null=True, upload_to='sede/'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='alias',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
