# Generated by Django 4.1.1 on 2023-11-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0002_rename_eventopersona_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evento',
        ),
    ]
