# Generated by Django 4.1.1 on 2023-11-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0002_sede_imagen_alter_sede_alias_alter_sede_nombre'),
        ('appPartido', '0004_evento'),
    ]

    operations = [
    ]
