# Generated by Django 4.1.1 on 2023-11-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0005_merge_20231102_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado_evento',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='estado_jugado',
            field=models.CharField(choices=[('J', 'JUGADO'), ('N', 'NO JUGADO'), ('E', 'EN JUEGO'), ('S', 'SUSPENDIDO')], default='N', max_length=2),
        ),
    ]
