# Generated by Django 4.1.1 on 2023-11-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0007_alter_descripcion_encuentro_tipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_encuentro',
            name='tipo_equipo',
            field=models.CharField(blank=True, choices=[('L', 'LOCAL'), ('V', 'VISITA')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='estado_jugado',
            field=models.CharField(choices=[('J', 'JUGADO'), ('N', 'NO JUGADO'), ('E', 'EN JUEGO'), ('S', 'SUSPENDIDO')], default='N', max_length=10, null=True),
        ),
    ]
