# Generated by Django 4.1.1 on 2023-11-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0008_alter_descripcion_encuentro_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_encuentro',
            name='resultado',
            field=models.CharField(choices=[('G', 'GANADO'), ('E', 'EMPATADO'), ('P', 'PERDIDO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='descripcion_encuentro',
            name='tipo_equipo',
            field=models.CharField(choices=[('L', 'LOCAL'), ('V', 'VISITA')], max_length=10),
        ),
    ]
