# Generated by Django 4.1.1 on 2023-11-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0009_alter_descripcion_encuentro_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_encuentro',
            name='tipo_equipo',
            field=models.CharField(choices=[('L', 'LOCAL'), ('V', 'VISITA')], max_length=10, null=True),
        ),
    ]
