# Generated by Django 4.1.1 on 2023-11-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0010_alter_descripcion_encuentro_tipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_encuentro',
            name='resultado',
            field=models.CharField(choices=[('G', 'GANADO'), ('E', 'EMPATADO'), ('P', 'PERDIDO')], max_length=2, null=True),
        ),
    ]
