# Generated by Django 4.1.1 on 2023-11-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0011_alter_descripcion_encuentro_resultado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estado',
        ),
    ]
