# Generated by Django 4.1.1 on 2023-11-11 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0012_alter_detalle_grupo_options'),
        ('appPartido', '0013_evento_competicion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='competicion_id',
            field=models.ForeignKey(db_column='competicion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.competicion'),
        ),
    ]
