# Generated by Django 4.1.1 on 2023-11-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0016_alter_descripcion_encuentro_goles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcion_encuentro',
            name='formacion',
        ),
        migrations.DeleteModel(
            name='formacion',
        ),
    ]
