# Generated by Django 4.1.1 on 2023-11-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0017_remove_descripcion_encuentro_formacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadisticas',
            fields=[
                ('estadisticas_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('posesion_balon', models.IntegerField()),
                ('pases_acertados', models.IntegerField()),
                ('tiros_desviados', models.IntegerField()),
                ('efectividad_pases', models.IntegerField()),
                ('tiros_arco', models.IntegerField()),
                ('tiros_esquina', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'estadisticas',
            },
        ),
    ]
