# Generated by Django 4.1.1 on 2023-11-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0018_estadisticas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='tiempo_extra',
            new_name='tiempo',
        ),
        migrations.RemoveField(
            model_name='descripcion_encuentro',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='estado_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tiempo_reglamentario',
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='descripcion_encuentro_id',
            field=models.ForeignKey(db_column='descripcion_encuentro_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.descripcion_encuentro'),
        ),
    ]
