# Generated by Django 4.1.1 on 2023-11-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0022_alter_encuentro_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadisticas',
            old_name='tiros_arco',
            new_name='tiros_directos_arco',
        ),
        migrations.RenameField(
            model_name='estadisticas',
            old_name='tiros_esquina',
            new_name='tiros_indirectos_arco',
        ),
    ]
