# Generated by Django 4.1.1 on 2023-11-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0023_rename_tiros_arco_estadisticas_tiros_directos_arco_and_more'),
        ('appPartido', '0025_evento_contrato_id1_evento_contrato_id2'),
    ]

    operations = [
    ]
