# Generated by Django 4.1.1 on 2023-11-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0026_merge_20231124_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_equipo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
