# Generated by Django 4.1.1 on 2023-11-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0027_evento_evento_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='contrato_id1',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='contrato_id2',
        ),
    ]
