# Generated by Django 4.1.1 on 2023-11-25 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0025_equipo_entrenador_id_tipo_equipo_estado_and_more'),
        ('appPartido', '0028_remove_evento_contrato_id1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='alineacion_id1',
            field=models.ForeignKey(blank=True, db_column='alineacion_id1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alineacion1', to='appEquipo.alineacion'),
        ),
        migrations.AddField(
            model_name='evento',
            name='alineacion_id2',
            field=models.ForeignKey(blank=True, db_column='alineacion_id2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alineacion2', to='appEquipo.alineacion'),
        ),
    ]
