# Generated by Django 4.1.1 on 2023-11-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0029_evento_alineacion_id1_evento_alineacion_id2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evento',
        ),
    ]
