# Generated by Django 4.1.1 on 2023-11-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0032_alter_evento_motivo'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='evento',
        #     name='tiempo',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
    ]
