# Generated by Django 4.1.1 on 2023-11-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0033_alter_evento_tiempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='tiempo',
        ),
    ]
