# Generated by Django 4.1.1 on 2023-11-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0036_remove_evento_evento_equipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='evento',
        ),
    ]
