# Generated by Django 4.1.1 on 2024-01-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0017_jornada'),
        ('appPartido', '0039_alter_encuentro_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='jornada',
            field=models.ForeignKey(blank=True, db_column='jornada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jornada', to='appCompeticion.jornada'),
        ),
    ]
