# Generated by Django 4.1.1 on 2024-01-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0040_encuentro_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
