# Generated by Django 4.1.1 on 2023-11-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('contrato_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(choices=[('P', 'PRÉSTAMO'), ('C', 'COMPRA'), ('L', 'LIBRE'), ('R', 'RENOVACIÓN'), ('S', 'SELECCIÓN')], default='C', max_length=1)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('dorsal', models.IntegerField(blank=True, null=True)),
                ('posicion_jugador', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'contrato',
            },
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('persona_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('estado', models.BooleanField()),
                ('foto', models.ImageField(blank=True, default='jugador/def_jugador.png', null=True, upload_to='jugador/foto/')),
            ],
            options={
                'verbose_name_plural': 'persona',
            },
        ),
        migrations.CreateModel(
            name='tipo_persona',
            fields=[
                ('tipo_persona_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'tipo_persona',
            },
        ),
    ]
