# Generated by Django 4.1.1 on 2023-11-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0003_tipo_arbitro_detalle_terna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='persona',
            field=models.ForeignKey(db_column='persona_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_persona', to='appContrato.persona'),
        ),
    ]
