# Generated by Django 4.1.1 on 2023-11-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0004_alter_contrato_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='ultimo_club',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='posicion_jugador',
            field=models.CharField(choices=[('DEL', 'DELANTERO'), ('CEN', 'CENTROCAMPISTA'), ('DEF', 'DEFENSA'), ('POR', 'PORTERO')], default='DEL', max_length=3),
        ),
    ]
