# Generated by Django 4.1.1 on 2023-11-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0005_remove_contrato_ultimo_club_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_terna',
            options={'verbose_name_plural': 'terna_arbitral'},
        ),
    ]
