# Generated by Django 4.1.1 on 2023-11-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0019_alter_alineacion_descripcion_encuentro_id'),
        ('appContrato', '0006_alter_detalle_terna_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='posicion_jugador',
            field=models.ForeignKey(db_column='posicion_jugador_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appEquipo.posicion_jugador'),
        ),
    ]
