# Generated by Django 4.1.1 on 2023-11-22 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0007_alter_contrato_posicion_jugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_persona',
            name='estado',
        ),
    ]
