# Generated by Django 4.1.1 on 2023-11-22 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0013_remove_organizacion_tipo_remove_pais_estado'),
        ('appContrato', '0008_remove_tipo_persona_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='organizacion_id',
            field=models.ForeignKey(db_column='organizacion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.organizacion'),
        ),
    ]
