"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!2gb-$ns@@#8m5)^ij!uzm1hgm)+$3acxb36pc64rx(p^201ly'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1','localhost']
# settings.py

ALLOWED_HOSTS = ['sistemafutbol.up.railway.app', 'otrodominio.com']  # Agrega 'sistemafutbol.up.railway.app' y otros dominios permitidos según sea necesario
CSRF_TRUSTED_ORIGINS = ['https://pryfutbolisticodjango-production.up.railway.app']

# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'admin_volt.apps.AdminVoltConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appCompeticion',
    'appContrato',
    'appEquipo',
    'appPartido',
    'debug_toolbar',
    'user',
]
X_FRAME_OPTIONS  =  "MISMOORIGIN" 
X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS  =  [ "seguridad.W019" ]
MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'project.custom_context_processor.listar_deportes'
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# # }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'pryFutbolisticoV4',
#         'USER': 'administrador',
#         'PASSWORD': 'administrador',
#         'HOST': 'containers-us-west-205.railway.app',  # si tienes otra dirección host debes remplazar esta
#         'PORT': '5977',  # si lo dejas vacío tomará el puerto por default
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'BDFUT',
        'USER': 'postgres',
        'PASSWORD': '*CAABbgaAC*AfceGFABAeAE*d-*55C24',
        'PGHOST': 'roundhouse.proxy.rlwy.net',  # si tienes otra dirección host debes remplazar esta
        'PGPORT': '55021',  # si lo dejas vacío tomará el puerto por default
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/a
import os

STATIC_URL = '/static/'

MEDIA_URL='/images/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS=[BASE_DIR / "static",]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# STATIC_ROOT='/home/virupqhv/calidad.virusgaming.gg/static'
#  STATIC_ROOT = BASE_DIR / 'static'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATIC_ROOT = BASE_DIR / '/static'
MEDIA_ROOT= BASE_DIR / 'static/images'

# STATIC_URL - '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# STATICFILES_DIRS=[os.path.join(BASE_DIR,'static'),]
# MEDIA_ROOT= [os.path.join(BASE_DIR,'static/images'),]
# # MEDIA_URL - '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL='user.User'

INTERNAL_APPS = [
    # ...
    "127.0.0.1",
    
    
    # ...
]