# Generated by Django 4.1.1 on 2023-11-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appCompeticion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alineacionEquipo',
            fields=[
                ('alineacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dorsal', models.IntegerField(null=True)),
                ('capitan', models.BooleanField(null=True)),
                ('estado', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name_plural': 'alineacionEquipo',
            },
        ),
        migrations.CreateModel(
            name='categoria_equipo',
            fields=[
                ('categoria_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categoria_equipo',
            },
        ),
        migrations.CreateModel(
            name='encuentro_persona',
            fields=[
                ('encuentro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pases', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('kmrecorridos', models.IntegerField()),
                ('pasestotales', models.IntegerField()),
                ('pases_acertados', models.IntegerField()),
                ('pases_errados', models.IntegerField()),
                ('minutosjugando', models.IntegerField()),
                ('expulsado', models.IntegerField()),
                ('sustituidos', models.IntegerField()),
                ('amonestado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'encuentro_persona',
            },
        ),
        migrations.CreateModel(
            name='posicion_jugador',
            fields=[
                ('posicion_jugador_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'posicion_jugador',
            },
        ),
        migrations.CreateModel(
            name='tipo_equipo',
            fields=[
                ('tipo_equipo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'tipo_equipo',
            },
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('equipo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipo/logo/')),
                ('vestimenta_principal', models.ImageField(blank=True, null=True, upload_to='equipo/vestimenta_principal/')),
                ('vestimenta_alterna', models.ImageField(blank=True, null=True, upload_to='equipo/vestimenta_secundaria/')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='equipo/portada/')),
                ('presidente', models.CharField(default='', max_length=50)),
                ('nombre', models.CharField(max_length=70)),
                ('siglas', models.CharField(max_length=3)),
                ('categoria_equipo', models.ForeignKey(db_column='categoria_equipo', on_delete=django.db.models.deletion.CASCADE, to='appEquipo.categoria_equipo')),
                ('deporte_id', models.ForeignKey(db_column='deporte_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.deporte')),
            ],
            options={
                'verbose_name_plural': 'equipo',
            },
        ),
    ]
