# Generated by Django 4.1.1 on 2023-11-02 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0002_initial'),
        ('appPartido', '0001_initial'),
        ('appEquipo', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alineacionEquipo',
            new_name='alineacion',
        ),
        migrations.AlterModelOptions(
            name='alineacion',
            options={'verbose_name_plural': 'alineacion'},
        ),
    ]
