# Generated by Django 4.1.1 on 2023-11-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0003_organizacion_patrocinador_detalle_patrocinador'),
        ('appEquipo', '0003_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='deporte_id',
            field=models.ForeignKey(db_column='deporte_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.deporte'),
        ),
    ]
