# Generated by Django 4.1.1 on 2023-11-02 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0003_rename_alineacionequipo_alineacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alineacion',
        ),
    ]
