# Generated by Django 4.1.1 on 2023-11-02 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0002_initial'),
        ('appPartido', '0003_delete_evento'),
        ('appEquipo', '0004_delete_alineacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='alineacion',
            fields=[
                ('alineacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dorsal', models.IntegerField(null=True)),
                ('capitan', models.BooleanField(null=True)),
                ('estado', models.BooleanField(null=True)),
                ('contrato_id', models.ForeignKey(db_column='contrato_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appContrato.contrato')),
                ('descripcion_encuentro_id', models.ForeignKey(db_column='descripcion_encuentro_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.descripcion_encuentro')),
                ('posicion_jugador_id', models.ForeignKey(db_column='posicion_jugador_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appEquipo.posicion_jugador')),
            ],
            options={
                'verbose_name_plural': 'alineacion',
            },
        ),
    ]
