# Generated by Django 4.1.1 on 2023-11-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0004_alter_equipo_deporte_id'),
        ('appEquipo', '0005_alineacion'),
    ]

    operations = [
    ]
