# Generated by Django 4.1.1 on 2023-11-02 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0005_merge_20231102_0121'),
        ('appEquipo', '0007_alter_encuentro_persona_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encuentro_persona',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='encuentro_persona',
            name='encuentro_id',
            field=models.ForeignKey(db_column='encuentro_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appPartido.encuentro'),
        ),
    ]
