# Generated by Django 4.1.1 on 2023-11-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0008_alter_encuentro_persona_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='encuentro_persona',
        ),
    ]
