# Generated by Django 4.1.1 on 2023-11-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0010_encuentro_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='encuentro_persona',
        ),
    ]
