# Generated by Django 4.1.1 on 2023-11-02 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0002_initial'),
        ('appPartido', '0005_merge_20231102_0121'),
        ('appEquipo', '0011_delete_encuentro_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='encuentro_persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pases', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('kmrecorridos', models.IntegerField()),
                ('pasestotales', models.IntegerField()),
                ('pases_acertados', models.IntegerField()),
                ('pases_errados', models.IntegerField()),
                ('minutosjugando', models.IntegerField()),
                ('expulsado', models.IntegerField()),
                ('sustituidos', models.IntegerField()),
                ('amonestado', models.BooleanField()),
                ('contrato_id', models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, to='appContrato.contrato')),
                ('encuentro_id', models.ForeignKey(db_column='encuentro_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.encuentro')),
                ('equipo_id', models.ForeignKey(db_column='equipo_id', on_delete=django.db.models.deletion.CASCADE, to='appEquipo.equipo')),
            ],
            options={
                'verbose_name_plural': 'encuentro_persona',
            },
        ),
        migrations.AddConstraint(
            model_name='encuentro_persona',
            constraint=models.UniqueConstraint(fields=('encuentro_id', 'equipo_id', 'contrato_id'), name='unique_encuentro_persona'),
        ),
    ]
