# Generated by Django 4.1.1 on 2023-11-02 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0012_encuentro_persona_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='encuentro_persona',
        ),
    ]
