# Generated by Django 4.1.1 on 2023-11-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0005_merge_20231102_0121'),
        ('appContrato', '0003_tipo_arbitro_detalle_terna'),
        ('appEquipo', '0014_encuentro_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alineacion',
            name='contrato_id',
            field=models.ForeignKey(db_column='contrato_id', on_delete=django.db.models.deletion.CASCADE, to='appContrato.contrato'),
        ),
        migrations.AlterField(
            model_name='alineacion',
            name='descripcion_encuentro_id',
            field=models.ForeignKey(db_column='descripcion_encuentro_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.descripcion_encuentro'),
        ),
    ]
