# Generated by Django 4.1.1 on 2023-11-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0003_tipo_arbitro_detalle_terna'),
        ('appEquipo', '0015_alter_alineacion_contrato_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alineacion',
            name='contrato_id',
            field=models.ForeignKey(db_column='contrato_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appContrato.contrato'),
        ),
    ]
