# Generated by Django 4.1.1 on 2023-11-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0016_alter_alineacion_contrato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro_persona',
            name='amonestado',
            field=models.BooleanField(null=True),
        ),
    ]
