# Generated by Django 4.1.1 on 2023-11-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0017_alter_encuentro_persona_amonestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro_persona',
            name='encuentro_persona_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
