# Generated by Django 4.1.1 on 2023-11-12 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0014_evento_competicion_id'),
        ('appEquipo', '0018_alter_encuentro_persona_encuentro_persona_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alineacion',
            name='descripcion_encuentro_id',
            field=models.ForeignKey(db_column='descripcion_encuentro_id', on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_encuentros', to='appPartido.descripcion_encuentro'),
        ),
    ]
