# Generated by Django 4.1.1 on 2023-11-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0019_alter_alineacion_descripcion_encuentro_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alineacion',
            name='formacion',
            field=models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-2-3-1', '4-2-3-1'), ('3-5-2', '3-5-2'), ('4-1-4-1', '4-1-4-1'), ('4-3-2-1', '4-3-2-1'), ('3-4-3', '3-4-3'), ('4-4-1-1', '4-4-1-1')], default='4-3-3', max_length=10),
        ),
    ]
