# Generated by Django 4.1.1 on 2023-11-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0006_alter_detalle_terna_options'),
        ('appEquipo', '0020_remove_encuentro_persona_expulsado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro_persona',
            name='contrato_id',
            field=models.ForeignKey(db_column='posicion_jugador', on_delete=django.db.models.deletion.CASCADE, related_name='encuentro_personas', to='appContrato.contrato'),
        ),
    ]
