# Generated by Django 4.1.1 on 2023-11-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0020_alineacion_formacion'),
        ('appEquipo', '0021_alter_encuentro_persona_contrato_id'),
    ]

    operations = [
    ]
