# Generated by Django 4.1.1 on 2023-11-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appContrato', '0010_remove_contrato_tipo_persona'),
        ('appEquipo', '0024_alter_encuentro_persona_contrato_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='entrenador_id',
            field=models.ForeignKey(db_column='contrato_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appContrato.contrato'),
        ),
        migrations.AddField(
            model_name='tipo_equipo',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='encuentro_persona',
        ),
    ]
