# Generated by Django 4.1.1 on 2023-11-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competicion',
            fields=[
                ('competicion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo_competicion', models.ImageField(blank=True, default='competicion/logo/logo_default.png', null=True, upload_to='competicion/logo/')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('fecha_inicio', models.DateField(blank=True, default='1990-12-12', null=True)),
                ('fecha_fin', models.DateField(blank=True, default='1990-12-12', null=True)),
            ],
            options={
                'verbose_name_plural': 'competicion',
            },
        ),
        migrations.CreateModel(
            name='deporte',
            fields=[
                ('deporte_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'deporte',
            },
        ),
        migrations.CreateModel(
            name='detalle_grupo',
            fields=[
                ('detalle_grupo_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'detalle_grupo',
            },
        ),
        migrations.CreateModel(
            name='detalle_patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'detalle_patrocinador',
            },
        ),
        migrations.CreateModel(
            name='fase',
            fields=[
                ('fase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'fase',
            },
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('grupo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='organizacion',
            fields=[
                ('organizacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_oficial', models.CharField(max_length=30)),
                ('siglas', models.CharField(default='', max_length=3)),
                ('descripcion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('F', 'FEDERACIÓN NACIONAL'), ('I', 'FEDERACIÓN INTERNACIONAL'), ('C', 'CONFEDERACIÓN'), ('L', 'LIGA')], default='I', max_length=1)),
                ('estado', models.BooleanField()),
                ('logo', models.ImageField(blank=True, default='organizacion/bandera_default.png', null=True, upload_to='organizacion/')),
            ],
            options={
                'verbose_name_plural': 'organizaciones',
            },
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('pais_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('sigla', models.CharField(default='', max_length=3)),
                ('logo_bandera', models.ImageField(blank=True, default='bandera/bandera_default.png', null=True, upload_to='bandera/')),
                ('estado', models.CharField(choices=[('SUSPENDIDO', 'Suspendido'), ('PROBACION', 'Probación'), ('NO_AFILIADO', 'No Afiliado'), ('SANCIONADO', 'Sancionado'), ('EN_INVESTIGACION', 'En Investigación'), ('MIEMBRO', 'Miembro')], default='MIEMBRO', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'paises',
            },
        ),
        migrations.CreateModel(
            name='patrocinador',
            fields=[
                ('patrocinador_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_patrocinador', models.CharField(max_length=50)),
                ('nombre_abreviado', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
                ('logo_1', models.ImageField(blank=True, default='patrocinador/logo_1/logo_default.png', upload_to='patrocinador/logo_1/')),
                ('logo_2', models.ImageField(blank=True, default='patrocinador/logo_2/logo_default.png', upload_to='patrocinador/logo_2/')),
            ],
            options={
                'verbose_name_plural': 'patrocinador',
            },
        ),
        migrations.CreateModel(
            name='tipo_competicion',
            fields=[
                ('tipo_competicion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'tipo_competicion',
            },
        ),
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('tabla_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ganado', models.IntegerField()),
                ('perdido', models.IntegerField()),
                ('empatado', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_contra', models.IntegerField()),
                ('tarjetas_amarillas', models.IntegerField()),
                ('tarjetas_rojas', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('competicion_id', models.ForeignKey(db_column='competicion_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.competicion')),
            ],
            options={
                'verbose_name_plural': 'tabla',
            },
        ),
    ]
