# Generated by Django 4.1.1 on 2023-11-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0006_merge_0004_alter_equipo_deporte_id_0005_alineacion'),
        ('appCompeticion', '0004_remove_grupo_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tabla',
            new_name='tabla_posicion',
        ),
        migrations.AlterModelOptions(
            name='tabla_posicion',
            options={'verbose_name_plural': 'tabla_posicion'},
        ),
    ]
