# Generated by Django 4.1.1 on 2023-11-04 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0005_rename_tabla_tabla_posicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicion',
            name='tipo_competicion_id',
        ),
        migrations.AddField(
            model_name='competicion',
            name='organizacion_id',
            field=models.ForeignKey(db_column='organizacion_id', default='1', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.organizacion'),
        ),
        migrations.DeleteModel(
            name='tipo_competicion',
        ),
    ]
