# Generated by Django 4.1.1 on 2023-11-05 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0006_remove_competicion_tipo_competicion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='organizacion_id',
            field=models.ForeignKey(db_column='organizacion_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.organizacion'),
        ),
    ]
