# Generated by Django 4.1.1 on 2023-11-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0007_alter_competicion_organizacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre_oficial',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='siglas',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='tipo',
            field=models.CharField(choices=[('F', 'FEDERACIÓN NACIONAL'), ('I', 'FEDERACIÓN INTERNACIONAL'), ('C', 'CONFEDERACIÓN'), ('L', 'LIGA'), ('L', 'ASOCIACIÓN')], default='I', max_length=1),
        ),
    ]
