# Generated by Django 4.1.1 on 2023-11-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0009_alter_detalle_grupo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_grupo',
            options={'verbose_name_plural': 'detalle_grupo'},
        ),
    ]
