# Generated by Django 4.1.1 on 2023-11-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0011_alter_detalle_grupo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_grupo',
            options={'verbose_name_plural': 'Grupo_competicion'},
        ),
    ]
