# Generated by Django 4.1.1 on 2023-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0014_organizacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='tipo',
            field=models.CharField(choices=[('F', 'FEDERACIÓN NACIONAL'), ('I', 'FEDERACIÓN INTERNACIONAL'), ('C', 'CONFEDERACIÓN'), ('L', 'LIGA'), ('A', 'ASOCIACIÓN')], default='I', max_length=1),
        ),
    ]
