# Generated by Django 4.1.1 on 2023-12-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0015_alter_organizacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicion',
            name='pais_id',
            field=models.ForeignKey(blank=True, db_column='pais_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.pais'),
        ),
    ]
