# Generated by Django 4.1.1 on 2024-01-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0016_alter_competicion_pais_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='jornada',
            fields=[
                ('jornada_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'jornada',
            },
        ),
    ]
