# Generated by Django 4.1.1 on 2024-01-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0017_jornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicion',
            name='deporte_id',
        ),
    ]
