# Generated by Django 4.1.1 on 2024-01-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0018_remove_competicion_deporte_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='jornadas',
            field=models.IntegerField(blank=True, db_column='jornada', null=True),
        ),
    ]
